name: 'Terraform'

on:
 workflow_dispatch:
  inputs:
    apply:
      description: 'Terraform apply'
      required: true
      default: ''
    destroy:
      description: 'Terraform destroy'
      required: true
      default: ''


jobs:
  terraform:
    name: "Marius-Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: 'us-east-1'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform plan
        id: plan
        run: terraform plan
        if:  github.event.inputs.apply == 'apply'

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve -var ami_id=`aws ec2 describe-images --region us-east-1 --owners self --output json | jq '.Images[] | {ImageId}' | jq --raw-output '.ImageId'  | tail -n 1`
        if:  github.event.inputs.apply == 'apply'

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
        if:  github.event.inputs.destroy == 'destroy'
